// Server-side Report PDF renderer.
//
// Takes a structured MonthlyReport and returns a PDF buffer via playwright-core.
// Same constraints as slide-render: local/dev only until prod Chromium lands in
// Sprint 11-12.

export type ReportPdfInput = {
  clientName: string;
  periodLabel: string;
  generatedAtLabel: string;
  summary: string;
  highlights: string[];
  lessons: string[];
  nextPillars: string[];
  counts: Array<{ label: string; value: string }>;
};

function escape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/**
 * Build a standalone HTML document for the monthly report. A4 portrait;
 * every section styled inline so we don't depend on CSS loading order or
 * external fonts at render time.
 */
export function buildReportHtml(input: ReportPdfInput): string {
  const list = (items: string[]): string =>
    items.length === 0
      ? '<p class="muted">—</p>'
      : `<ul>${items.map((i) => `<li>${escape(i)}</li>`).join("")}</ul>`;

  const countsRow = input.counts
    .map(
      (c) => `
    <div class="stat">
      <div class="stat-label">${escape(c.label)}</div>
      <div class="stat-value">${escape(c.value)}</div>
    </div>`,
    )
    .join("");

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>${escape(input.clientName)} · ${escape(input.periodLabel)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  html, body { font-family: "Inter", system-ui, -apple-system, sans-serif; color: #1a1a1a; background: #fff; }
  body { padding: 48px 56px; line-height: 1.4; }
  h1 { font-size: 32px; font-weight: 700; letter-spacing: -0.01em; margin-bottom: 4px; }
  h2 { font-size: 18px; font-weight: 600; margin: 28px 0 8px; }
  p { font-size: 13px; }
  ul { margin-left: 18px; font-size: 13px; }
  li { margin-bottom: 4px; }
  .kicker { font-size: 10px; text-transform: uppercase; letter-spacing: 0.16em; color: #888; margin-bottom: 12px; }
  .meta { font-size: 11px; color: #888; margin-top: 4px; margin-bottom: 24px; }
  .muted { font-size: 12px; color: #999; font-style: italic; }
  .stats {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 8px;
    margin: 16px 0 28px;
    border: 1px solid #e5e5e5;
    border-radius: 8px;
    padding: 14px;
  }
  .stat { padding: 4px 6px; }
  .stat-label { font-size: 9px; text-transform: uppercase; letter-spacing: 0.1em; color: #888; margin-bottom: 2px; }
  .stat-value { font-size: 18px; font-weight: 600; }
  .summary { font-size: 14px; background: #f7f6f3; padding: 14px 16px; border-radius: 6px; }
  footer { margin-top: 32px; padding-top: 14px; border-top: 1px solid #eee; font-size: 10px; color: #aaa; }
</style>
</head>
<body>
  <div class="kicker">Nest · Monthly recap</div>
  <h1>${escape(input.clientName)}</h1>
  <div class="meta">${escape(input.periodLabel)} · Generated ${escape(input.generatedAtLabel)}</div>

  <div class="stats">${countsRow}</div>

  <section>
    <h2>Summary</h2>
    <p class="summary">${escape(input.summary)}</p>
  </section>

  <section>
    <h2>Highlights</h2>
    ${list(input.highlights)}
  </section>

  <section>
    <h2>Lessons</h2>
    ${list(input.lessons)}
  </section>

  <section>
    <h2>Next-month pillars</h2>
    ${list(input.nextPillars)}
  </section>

  <footer>
    Generated by Nest · ${escape(input.generatedAtLabel)}
  </footer>
</body>
</html>`;
}

/**
 * Render a report HTML document to a PDF buffer using playwright-core's
 * bundled Chromium. Dynamic import keeps the ~50 MB binary reference out of
 * cold start paths for unrelated routes.
 */
export async function renderReportToPdf(html: string): Promise<Buffer> {
  const { chromium } = await import("playwright-core");
  const browser = await chromium.launch();
  try {
    const context = await browser.newContext({
      viewport: { width: 794, height: 1123 }, // A4 @ 96dpi
    });
    const page = await context.newPage();
    await page.setContent(html, { waitUntil: "domcontentloaded" });
    const pdf = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "0", right: "0", bottom: "0", left: "0" },
    });
    return pdf;
  } finally {
    await browser.close();
  }
}
