#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Ensaio: monta o banco novo e confere, sem tocar na produção. A virada das
# chaves — o único passo irreversível — fica de fora.
ENSAIO=0
[ "${1:-}" = "--ensaio" ] && ENSAIO=1
TOTAL_STAGES=12
[ "$ENSAIO" = "1" ] && TOTAL_STAGES=9

# A conexão direta (db.<ref>.supabase.co) só publica endereço IPv6. O Docker,
# que é onde o supabase CLI roda o pg_dump, usa rede IPv4 por padrão: ele
# RESOLVE o IPv6 e não ALCANÇA. O dump falha no meio sem dizer por quê.
#
# O Session pooler publica IPv4 e é o que a própria documentação do Supabase
# manda usar por padrão. Esta checagem existe porque a string errada está a um
# clique de distância da certa, no mesmo painel.
reject_direct() {
  case "$1" in
    *@db.*.supabase.co*)
      say ""
      say "Essa é a conexão DIRETA, e ela não funciona aqui."
      say ""
      say "O host db.<ref>.supabase.co só tem IPv6. O dump roda dentro do"
      say "Docker, cuja rede padrão é IPv4 — ele resolve o endereço e não"
      say "consegue alcançar."
      say ""
      step "No painel, no seletor do topo do Connect, troque para:"
      say "   Session pooler"
      say ""
      say "A string certa tem 'pooler.supabase.com' no host e o usuário"
      say "no formato postgres.<ref>."
      say ""
      return 1
      ;;
  esac
  return 0
}

# `supabase db dump -s auth` devolve só os TIPOS do schema auth: o CLI filtra
# de propósito os schemas que o Supabase gerencia, então as tabelas e os dados
# não vêm. Confirmado num arquivo de 46 KB com zero linhas de COPY.
#
# pg_dump direto resolve, e de quebra evita o Docker — o pooler é IPv4, que é
# justamente o que a rede do contêiner não alcançava.
#
# Duas tabelas bastam para as pessoas continuarem entrando:
#   auth.users      — as contas, com a senha cifrada
#   auth.identities — o vínculo com o provedor (email, Google)
# Sessões e refresh tokens ficam de fora de propósito: são efêmeros, e perdê-los
# só significa que cada um faz login de novo uma vez.
dump_auth() {
  pg_dump --data-only --no-owner --no-privileges \
    -t auth.users -t auth.identities \
    "$1" > "$DUMP_DIR/auth.sql" 2>"$DUMP_DIR/auth.err" || {
      say "pg_dump falhou:"
      sed 's/^/     /' "$DUMP_DIR/auth.err" | head -4
      return 1
    }
  grep -qE "^COPY auth\.users|INSERT INTO auth\.users" "$DUMP_DIR/auth.sql"
}

banner "Nest · migrar o Supabase para São Paulo"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Antes de começar"
if [ "$ENSAIO" = "1" ]; then
  say "MODO ENSAIO."
  say ""
  say "Monta o banco novo em São Paulo, restaura os dados e confere que"
  say "tudo chegou — e PARA antes de trocar as chaves."
  say ""
  say "A produção não é tocada. Ninguém perde nada. O app continua"
  say "falando com a Virgínia o tempo todo."
  say ""
  say "Serve para responder \"vai dar certo?\" antes de valer."
else
  say "MIGRAÇÃO REAL — a produção MUDA."
  say ""
  say "Entre o dump e a troca das chaves, o app continua no ar apontando"
  say "para o banco ANTIGO. Tudo que alguém gravar nesse intervalo — uma"
  say "tarefa, uma aprovação, uma mensagem — entra no banco velho e NÃO"
  say "existe no novo. Some, sem erro e sem aviso."
  say ""
  say "Faça fora do horário do estúdio, com a equipe avisada."
fi
say ""
say "Por que: uma consulta trivial leva 459ms hoje, medida pelo /api/health."
say "Uma tela faz 5 a 10 delas, o que dá os 3 segundos por clique."
say ""
step "Precisa ter: supabase CLI, psql, e o Docker rodando."
if [ "$ENSAIO" = "1" ]; then
  confirm "Pode começar o ensaio?"
else
  confirm "A equipe está avisada e é uma boa hora para o sistema cair?"
fi

command -v psql >/dev/null || { say "psql não encontrado. Instale o postgresql-client."; exit 1; }
docker info >/dev/null 2>&1 || { say "Docker não está rodando — o dump precisa dele."; exit 1; }

# ── 2 ─────────────────────────────────────────────────────────────────────
DUMP_DIR="$(pwd)/.migracao-supabase"
REUSAR=0
if [ -s "$DUMP_DIR/schema.sql" ] && [ -s "$DUMP_DIR/data.sql" ]; then
  # Esta etapa só existe quando há dump anterior, então entra na conta aqui
  # em vez de deixar o rodapé prometer um total que não bate.
  TOTAL_STAGES=$((TOTAL_STAGES + 1))
  stage "Dump anterior encontrado"
  say "Já existe um dump nesta pasta, de uma execução anterior:"
  say ""
  ls -lh "$DUMP_DIR"/*.sql 2>/dev/null | awk '{print "   " $9 "  " $5}'
  say ""
  say "Reaproveitar pula as etapas 2, 3 e 4 — que é onde você já passou"
  say "quatro vezes. Só não reaproveite se a produção mudou desde então."
  say ""
  if confirm "Reaproveitar este dump?"; then
    REUSAR=1

    # Reaproveitar só é seguro se os logins estiverem cobertos. Sem isto, o
    # restore roda inteiro e ninguém consegue entrar depois — e isso só
    # aparece na virada, que é tarde demais para descobrir.
    if [ -s "$DUMP_DIR/auth.sql" ]; then
      AUTH_FILE="$DUMP_DIR/auth.sql"
      say "auth.sql presente — os logins estão cobertos."
    elif grep -qE 'COPY "?auth"?\."?users"?' "$DUMP_DIR/data.sql" 2>/dev/null; then
      say "Os logins estão dentro do data.sql."
    else
      say ""
      say "Este dump NÃO tem os logins — nem auth.sql, nem dentro do data.sql."
      say "Restaurar assim deixaria todo mundo sem entrar."
      say ""
      say "Só falta isso. Preciso da conexão do projeto ATUAL uma vez,"
      say "e faço só o dump do auth — segundos, não o dump inteiro."
      say ""
      while :; do
        ask_secret OLD_DB_URL "Cole a connection string do projeto ATUAL:"
        reject_direct "$OLD_DB_URL" && break
      done
      if dump_auth "$OLD_DB_URL"; then
        AUTH_FILE="$DUMP_DIR/auth.sql"
        say "Logins capturados: $(grep -cE "^[0-9a-f-]{36}\\t" "$DUMP_DIR/auth.sql" || echo '?') conta(s)."
      else
        say ""
        say "Não consegui capturar os logins. PARANDO — seguir daqui"
        say "deixaria todo mundo sem entrar, e só apareceria na virada."
        exit 1
      fi
    fi
    pause
  fi
fi

if [ "$REUSAR" = "0" ]; then
stage "Conexão do projeto ATUAL"
say "Vamos pegar a string de conexão do projeto que existe hoje."
open_url "https://supabase.com/dashboard/project/wntrsavneabdcrztwudf/settings/database"
step "Abra Connect e, no seletor do topo, escolha SESSION POOLER."
step "Não use Direct connection: ela é IPv6 e o Docker não alcança."
step "Copie a URI inteira e troque [YOUR-PASSWORD] pela senha real do banco."
while :; do
  ask_secret OLD_DB_URL "Cole a connection string do projeto ATUAL:"
  reject_direct "$OLD_DB_URL" && break
done

say ""
say "Testando a conexão..."
psql "$OLD_DB_URL" -c 'select 1' >/dev/null 2>&1 \
  || { say "Não consegui conectar. Confira a senha e tente de novo."; exit 1; }
say "Conectou."
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
if [ "$REUSAR" = "0" ]; then
stage "Dump: papéis, schema e dados"
say "Três arquivos, na ordem que o restore vai precisar."
mkdir -p "$DUMP_DIR"
say "Salvando em $DUMP_DIR"
say ""

step "1/3 papéis..."
npx supabase db dump --db-url "$OLD_DB_URL" -f "$DUMP_DIR/roles.sql" --role-only
step "2/3 schema..."
npx supabase db dump --db-url "$OLD_DB_URL" -f "$DUMP_DIR/schema.sql"
step "3/3 dados..."
npx supabase db dump --db-url "$OLD_DB_URL" -f "$DUMP_DIR/data.sql" --use-copy --data-only \
  -x "storage.buckets_vectors" -x "storage.vector_indexes"

say ""
say "Tamanhos:"
ls -lh "$DUMP_DIR"/*.sql | awk '{print "   " $9 "  " $5}'

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Verificar se os logins vieram junto"
say "A documentação do Supabase NÃO afirma que auth.users entra no dump."
say "É a diferença entre todo mundo manter o login e ninguém entrar."
say "Então conferimos agora, antes de qualquer passo irreversível."
say ""

# `grep -c` imprime 0 e sai com 1 quando não acha nada, então o `|| echo 0`
# que estava aqui produzia "0\n0" — o teste numérico quebrava, o `if` caía no
# else, e a mensagem dizia "os logins estão no dump" quando não estavam.
# A checagem escrita para evitar o desastre falhava ABERTA.
# O dump escreve `COPY "auth"."users"` — com aspas ENTRE as partes. Procurar
# por `auth\.users` não casa, e foi assim que eu concluí que os logins não
# vinham no dump quando vinham desde sempre, e depois montei um segundo dump
# que colidiu por chave duplicada.
AUTH_IN_DATA=$(grep -cE 'COPY "?auth"?\."?users"?' "$DUMP_DIR/data.sql" 2>/dev/null || true)
LIVE_USERS=$(psql "$OLD_DB_URL" -tAc 'select count(*) from auth.users' 2>/dev/null | tr -d ' ' || true)

say "  usuários no banco atual : ${LIVE_USERS:-?}"
say "  auth.users no data.sql  : ${AUTH_IN_DATA:-0}"
say ""

if [ "${AUTH_IN_DATA:-0}" -gt 0 ] 2>/dev/null; then
  say "Os logins vieram no dump principal."
  pause
else
  say "O dump principal NÃO traz os logins — confirmado, não suposto."
  say "Fazendo um dump do schema auth agora."
  say ""
  if dump_auth "$OLD_DB_URL"; then
    AUTH_FILE="$DUMP_DIR/auth.sql"
    say "Logins capturados — auth.sql entra no restore."
  else
    say ""
    say "Não consegui capturar os logins. PARANDO — seguir daqui deixaria"
    say "todo mundo sem entrar, e só apareceria na virada."
    exit 1
  fi
  pause
fi

fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Criar o projeto novo em São Paulo"
open_url "https://supabase.com/dashboard/new"
step "Region: South America (São Paulo) — sa-east-1. Confira com atenção."
step "Plano: o mesmo do atual, para não perder backup diário."
step "Guarde a senha do banco que ele gerar — ela não aparece de novo."
say ""
OLD_REF="wntrsavneabdcrztwudf"
while :; do
  ask NEW_REF "Cole o Reference ID do projeto NOVO:"
  if [ "$NEW_REF" = "$OLD_REF" ]; then
    say ""
    say "Esse é o ref da PRODUÇÃO."
    say ""
    say "Restaurar o dump nele sobrescreveria o banco que está no ar."
    say "O projeto novo é outro — o que você criou em São Paulo."
    say ""
    continue
  fi
  [ -n "$NEW_REF" ] && break
done
write_env NEW_SUPABASE_REF "$NEW_REF"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Extensões — NÃO habilite pelo painel"
say "ERRADO: habilitar vector e pg_trgm pelo painel antes do restore."
say ""
say "O painel instala no schema `extensions`. As migrations deste projeto"
say "as puseram em `public`, e é isso que o dump recria — mas com"
say "IF NOT EXISTS, que vira no-op quando a extensão já existe em outro"
say "schema. Resultado: `public.vector` não existe e o restore morre na"
say "primeira função que usa esse tipo."
say ""
say "O dump cria as três sozinho, no lugar certo. Não faça nada aqui."
open_url "https://supabase.com/dashboard/project/$NEW_REF/database/extensions"
step "Se você já habilitou alguma pelo painel, o restore derruba e recria."
confirm "Entendido — seguir sem habilitar nada?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Restaurar no projeto novo"
open_url "https://supabase.com/dashboard/project/$NEW_REF/settings/database"
step "Copie a string do projeto NOVO — SESSION POOLER, não a direta."
while :; do
  ask_secret NEW_DB_URL "Cole a connection string do projeto NOVO:"
  reject_direct "$NEW_DB_URL" || continue
  case "$NEW_DB_URL" in
    *"$OLD_REF"*)
      say ""
      say "Essa string aponta para a PRODUÇÃO. Restaurar aqui destruiria"
      say "o banco que está no ar. Use a string do projeto de São Paulo."
      say ""
      continue
      ;;
  esac
  break
done

psql "$NEW_DB_URL" -c 'select 1' >/dev/null 2>&1 \
  || { say "Não consegui conectar no projeto novo."; exit 1; }

say ""
say "Restaurando. Uma transação só: ou entra tudo, ou não entra nada."
confirm "Pode restaurar?"

# `ALTER ROLE supabase_admin` é recusado: papel reservado, só superusuário
# mexe. E o arquivo inteiro só ajusta statement_timeout, que o projeto novo já
# traz no padrão — então filtrar a linha não perde nada.
grep -v 'supabase_admin' "$DUMP_DIR/roles.sql" > "$DUMP_DIR/roles.filtrado.sql"

psql --single-transaction --variable ON_ERROR_STOP=1 \
  --file "$DUMP_DIR/roles.filtrado.sql" \
  --file "$DUMP_DIR/schema.sql" \
  --command 'SET session_replication_role = replica' \
  ${AUTH_FILE:+--file "$AUTH_FILE"} \
  --file "$DUMP_DIR/data.sql" \
  --dbname "$NEW_DB_URL"

say ""
say "Conferindo o que chegou:"
psql "$NEW_DB_URL" -tAc "select 'clientes: '||count(*) from public.clients" 2>/dev/null || true
psql "$NEW_DB_URL" -tAc "select 'tarefas: '||count(*) from public.tasks" 2>/dev/null || true
psql "$NEW_DB_URL" -tAc "select 'logins: '||count(*) from auth.users" 2>/dev/null || true
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Realtime"
say "A migration 040 põe a tabela messages na publicação de realtime."
say "Isso não atravessa o dump — o chat fica mudo sem reativar."
open_url "https://supabase.com/dashboard/project/$NEW_REF/database/publications"
step "Em supabase_realtime, marque a tabela: messages"
confirm "Realtime ligado para messages?"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Storage: os três buckets"
say "Os arquivos NÃO vão no dump — só as linhas de storage.buckets vão."
say "Sem isto, toda imagem de marca, todo carrossel e todo reel do app"
say "vira 404 contra um bucket que existe e está vazio."
say ""
step "brand-assets  — logos e materiais de marca"
step "creatives     — carrosséis renderizados"
step "reel-videos   — vídeos"
say ""
say "Precisamos da chave service_role dos DOIS projetos."
say "A do projeto novo você já vai copiar na próxima etapa; pegue as duas agora."
say ""

open_url "https://supabase.com/dashboard/project/wntrsavneabdcrztwudf/settings/api-keys"
ask_secret OLD_SERVICE_KEY "service_role do projeto ANTIGO:"
open_url "https://supabase.com/dashboard/project/$NEW_REF/settings/api-keys"
ask OLD_URL_VALUE "Project URL do projeto ANTIGO:"
ask NEW_URL_VALUE "Project URL do projeto NOVO:"
ask_secret NEW_SERVICE_KEY "service_role do projeto NOVO:"

say ""
say "Primeiro uma simulação, que não grava nada:"
OLD_URL="$OLD_URL_VALUE" OLD_SERVICE_KEY="$OLD_SERVICE_KEY" \
NEW_URL="$NEW_URL_VALUE" NEW_SERVICE_KEY="$NEW_SERVICE_KEY" \
  node scripts/copy-storage.mjs --dry-run

say ""
confirm "A contagem de arquivos bate com o que você espera?"

OLD_URL="$OLD_URL_VALUE" OLD_SERVICE_KEY="$OLD_SERVICE_KEY" \
NEW_URL="$NEW_URL_VALUE" NEW_SERVICE_KEY="$NEW_SERVICE_KEY" \
  node scripts/copy-storage.mjs

say ""
say "Se caiu no meio, rode a linha acima de novo — ele pula o que já copiou."
pause

# ── 10 ────────────────────────────────────────────────────────────────────
if [ "$ENSAIO" = "1" ]; then
  stage "Ensaio concluído"
  say "O banco novo está em São Paulo, com os dados e os arquivos."
  say "A produção não foi tocada — o app segue na Virgínia."
  say ""
  say "Confira no painel do projeto novo que os números batem com o que"
  say "a etapa 7 imprimiu. Se baterem, a migração de verdade é este mesmo"
  say "roteiro sem --ensaio, e as etapas 1 a 9 vão muito mais rápido"
  say "porque o projeto novo já existe."
  say ""
  say "Deixe o projeto novo de pé. Ele não atrapalha nada parado."
  finish
fi

stage "Chaves novas para a Vercel"
say "A PARTIR DAQUI A PRODUÇÃO MUDA. Antes disto, nada foi tocado."
confirm "A equipe está avisada e ninguém está usando o sistema?"
say "Das 27 variáveis do app, só estas três mudam."
say "A URL e a service_role do projeto novo você já colou na etapa 9."
say "Falta só a chave anon."
open_url "https://supabase.com/dashboard/project/$NEW_REF/settings/api-keys"
ask_secret NEW_ANON "Chave anon / publishable do projeto NOVO:"

write_env NEXT_PUBLIC_SUPABASE_URL "$NEW_URL_VALUE"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEW_ANON"
write_env SUPABASE_SERVICE_ROLE_KEY "$NEW_SERVICE_KEY"

say ""
open_url "https://vercel.com/dashboard"
step "Projeto nest → Settings → Environment Variables"
step "Atualize as três em Production, depois Redeploy."
confirm "Vercel atualizada e redeploy disparado?"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "O ref no repositório"
say "O ref antigo está escrito em dois scripts do package.json."
say "Sem trocar, o types:gen passa a ler o banco errado — e o job"
say "types-drift do CI reporta divergência para sempre."
say ""
step "Trocar wntrsavneabdcrztwudf por $NEW_REF em:"
say "   package.json  → types:gen e types:check"
say "   ROADMAP.md    → linha 9 e 10"
say ""
confirm "Quer que eu troque agora com sed?"
sed -i.bak "s/wntrsavneabdcrztwudf/$NEW_REF/g" package.json ROADMAP.md && rm -f package.json.bak ROADMAP.md.bak
say "Trocado. Rode: npm run types:gen && npm run types:check"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Medir, e só então desligar o antigo"
say "O mesmo instrumento que diagnosticou o problema mede a cura."
say ""
step "Abrindo o health check da produção..."
open_url "https://nest-six-beta.vercel.app/api/health"
say ""
say "Procure latencyMs no JSON:"
say "   antes  : 459ms   (banco na Virgínia)"
say "   esperado: menos de 30ms   (banco em São Paulo)"
say ""
say "Depois entre no app e confira: login, um cliente, uma tarefa,"
say "o chat (realtime), e uma imagem de marca (storage)."
say ""
say "NÃO apague o projeto antigo hoje. Deixe-o parado por uma semana —"
say "é o seu botão de desfazer, e ele custa menos que uma restauração."
confirm "Tudo funcionando e o projeto antigo preservado?"

finish
