#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

banner "Nest · migrar o Supabase para São Paulo"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Antes de começar"
say "Isto move o banco de produção de us-east-1 para sa-east-1."
say ""
say "Por que: uma consulta trivial leva 459ms hoje, medida pelo /api/health."
say "Uma tela faz 5 a 10 delas, o que dá os 3 segundos por clique."
say ""
say "O sistema fica INDISPONÍVEL entre o dump e a virada das chaves."
say "Faça isto fora do horário do estúdio."
say ""
step "Precisa ter: supabase CLI, psql, e o Docker rodando."
confirm "Tudo isso está pronto e é uma boa hora?"

command -v psql >/dev/null || { say "psql não encontrado. Instale o postgresql-client."; exit 1; }
docker info >/dev/null 2>&1 || { say "Docker não está rodando — o dump precisa dele."; exit 1; }

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Conexão do projeto ATUAL"
say "Vamos pegar a string de conexão do projeto que existe hoje."
open_url "https://supabase.com/dashboard/project/wntrsavneabdcrztwudf/settings/database"
step "Abra o painel Connect e escolha 'Session pooler'."
step "Copie a URI inteira e troque [YOUR-PASSWORD] pela senha real do banco."
ask_secret OLD_DB_URL "Cole a connection string do projeto ATUAL:"

say ""
say "Testando a conexão..."
psql "$OLD_DB_URL" -c 'select 1' >/dev/null 2>&1 \
  || { say "Não consegui conectar. Confira a senha e tente de novo."; exit 1; }
say "Conectou."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Dump: papéis, schema e dados"
say "Três arquivos, na ordem que o restore vai precisar."
DUMP_DIR="$(pwd)/.migracao-supabase"
mkdir -p "$DUMP_DIR"
say "Salvando em $DUMP_DIR"
say ""

step "1/3 papéis..."
npx supabase db dump --db-url "$OLD_DB_URL" -f "$DUMP_DIR/roles.sql" --role-only
step "2/3 schema..."
npx supabase db dump --db-url "$OLD_DB_URL" -f "$DUMP_DIR/schema.sql"
step "3/3 dados..."
npx supabase db dump --db-url "$OLD_DB_URL" -f "$DUMP_DIR/data.sql" --use-copy --data-only \
  -x "storage.buckets_vectors" -x "storage.vector_indexes"

say ""
say "Tamanhos:"
ls -lh "$DUMP_DIR"/*.sql | awk '{print "   " $9 "  " $5}'

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Verificar se os logins vieram junto"
say "A documentação do Supabase NÃO afirma que auth.users entra no dump."
say "É a diferença entre todo mundo manter o login e ninguém entrar."
say "Então conferimos agora, antes de qualquer passo irreversível."
say ""

AUTH_ROWS=$(grep -c "^COPY auth\.users\|INSERT INTO auth\.users" "$DUMP_DIR/data.sql" 2>/dev/null || echo 0)
LIVE_USERS=$(psql "$OLD_DB_URL" -tAc 'select count(*) from auth.users' 2>/dev/null || echo "?")

say "  usuários no banco atual : $LIVE_USERS"
say "  auth.users no dump     : $AUTH_ROWS bloco(s)"
say ""

if [ "$AUTH_ROWS" -eq 0 ]; then
  say "O dump NÃO traz os logins."
  say ""
  step "Rode também, antes de continuar:"
  say "   npx supabase db dump --db-url \"\$OLD_DB_URL\" -s auth -f $DUMP_DIR/auth.sql"
  step "E inclua auth.sql no restore da etapa 7."
  confirm "Fez o dump de auth e vai incluí-lo no restore?"
else
  say "Os logins estão no dump. Seguimos."
  pause
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Criar o projeto novo em São Paulo"
open_url "https://supabase.com/dashboard/new"
step "Region: South America (São Paulo) — sa-east-1. Confira com atenção."
step "Plano: o mesmo do atual, para não perder backup diário."
step "Guarde a senha do banco que ele gerar — ela não aparece de novo."
say ""
ask NEW_REF "Cole o Reference ID do projeto NOVO:"
write_env NEW_SUPABASE_REF "$NEW_REF"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Extensões — ANTES do restore"
say "Três extensões que este schema usa. Se faltarem, o restore quebra no meio."
open_url "https://supabase.com/dashboard/project/$NEW_REF/database/extensions"
step "Habilite: vector   (embeddings do content-engine, migration 006)"
step "Habilite: pgcrypto (gen_random_uuid em toda tabela)"
step "Habilite: pg_trgm  (busca por similaridade)"
confirm "As três estão habilitadas no projeto NOVO?"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Restaurar no projeto novo"
open_url "https://supabase.com/dashboard/project/$NEW_REF/settings/database"
step "Copie a connection string do projeto NOVO (Session pooler, com a senha)."
ask_secret NEW_DB_URL "Cole a connection string do projeto NOVO:"

psql "$NEW_DB_URL" -c 'select 1' >/dev/null 2>&1 \
  || { say "Não consegui conectar no projeto novo."; exit 1; }

say ""
say "Restaurando. Uma transação só: ou entra tudo, ou não entra nada."
confirm "Pode restaurar?"

psql --single-transaction --variable ON_ERROR_STOP=1 \
  --file "$DUMP_DIR/roles.sql" \
  --file "$DUMP_DIR/schema.sql" \
  --command 'SET session_replication_role = replica' \
  --file "$DUMP_DIR/data.sql" \
  --dbname "$NEW_DB_URL"

say ""
say "Conferindo o que chegou:"
psql "$NEW_DB_URL" -tAc "select 'clientes: '||count(*) from public.clients" 2>/dev/null || true
psql "$NEW_DB_URL" -tAc "select 'tarefas: '||count(*) from public.tasks" 2>/dev/null || true
psql "$NEW_DB_URL" -tAc "select 'logins: '||count(*) from auth.users" 2>/dev/null || true
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Realtime"
say "A migration 040 põe a tabela messages na publicação de realtime."
say "Isso não atravessa o dump — o chat fica mudo sem reativar."
open_url "https://supabase.com/dashboard/project/$NEW_REF/database/publications"
step "Em supabase_realtime, marque a tabela: messages"
confirm "Realtime ligado para messages?"

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Storage: os três buckets"
say "Os arquivos NÃO vão no dump — só as linhas de storage.buckets vão."
say "Sem isto, toda imagem de marca, todo carrossel e todo reel do app"
say "vira 404 contra um bucket que existe e está vazio."
say ""
step "brand-assets  — logos e materiais de marca"
step "creatives     — carrosséis renderizados"
step "reel-videos   — vídeos"
say ""
say "Precisamos da chave service_role dos DOIS projetos."
say "A do projeto novo você já vai copiar na próxima etapa; pegue as duas agora."
say ""

open_url "https://supabase.com/dashboard/project/wntrsavneabdcrztwudf/settings/api-keys"
ask_secret OLD_SERVICE_KEY "service_role do projeto ANTIGO:"
open_url "https://supabase.com/dashboard/project/$NEW_REF/settings/api-keys"
ask OLD_URL_VALUE "Project URL do projeto ANTIGO:"
ask NEW_URL_VALUE "Project URL do projeto NOVO:"
ask_secret NEW_SERVICE_KEY "service_role do projeto NOVO:"

say ""
say "Primeiro uma simulação, que não grava nada:"
OLD_URL="$OLD_URL_VALUE" OLD_SERVICE_KEY="$OLD_SERVICE_KEY" \
NEW_URL="$NEW_URL_VALUE" NEW_SERVICE_KEY="$NEW_SERVICE_KEY" \
  node scripts/copy-storage.mjs --dry-run

say ""
confirm "A contagem de arquivos bate com o que você espera?"

OLD_URL="$OLD_URL_VALUE" OLD_SERVICE_KEY="$OLD_SERVICE_KEY" \
NEW_URL="$NEW_URL_VALUE" NEW_SERVICE_KEY="$NEW_SERVICE_KEY" \
  node scripts/copy-storage.mjs

say ""
say "Se caiu no meio, rode a linha acima de novo — ele pula o que já copiou."
pause

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Chaves novas para a Vercel"
say "Das 27 variáveis do app, só estas três mudam."
say "A URL e a service_role do projeto novo você já colou na etapa 9."
say "Falta só a chave anon."
open_url "https://supabase.com/dashboard/project/$NEW_REF/settings/api-keys"
ask_secret NEW_ANON "Chave anon / publishable do projeto NOVO:"

write_env NEXT_PUBLIC_SUPABASE_URL "$NEW_URL_VALUE"
write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$NEW_ANON"
write_env SUPABASE_SERVICE_ROLE_KEY "$NEW_SERVICE_KEY"

say ""
open_url "https://vercel.com/dashboard"
step "Projeto nest → Settings → Environment Variables"
step "Atualize as três em Production, depois Redeploy."
confirm "Vercel atualizada e redeploy disparado?"

# ── 11 ────────────────────────────────────────────────────────────────────
stage "O ref no repositório"
say "O ref antigo está escrito em dois scripts do package.json."
say "Sem trocar, o types:gen passa a ler o banco errado — e o job"
say "types-drift do CI reporta divergência para sempre."
say ""
step "Trocar wntrsavneabdcrztwudf por $NEW_REF em:"
say "   package.json  → types:gen e types:check"
say "   ROADMAP.md    → linha 9 e 10"
say ""
confirm "Quer que eu troque agora com sed?"
sed -i.bak "s/wntrsavneabdcrztwudf/$NEW_REF/g" package.json ROADMAP.md && rm -f package.json.bak ROADMAP.md.bak
say "Trocado. Rode: npm run types:gen && npm run types:check"

# ── 12 ────────────────────────────────────────────────────────────────────
stage "Medir, e só então desligar o antigo"
say "O mesmo instrumento que diagnosticou o problema mede a cura."
say ""
step "Abrindo o health check da produção..."
open_url "https://nest-six-beta.vercel.app/api/health"
say ""
say "Procure latencyMs no JSON:"
say "   antes  : 459ms   (banco na Virgínia)"
say "   esperado: menos de 30ms   (banco em São Paulo)"
say ""
say "Depois entre no app e confira: login, um cliente, uma tarefa,"
say "o chat (realtime), e uma imagem de marca (storage)."
say ""
say "NÃO apague o projeto antigo hoje. Deixe-o parado por uma semana —"
say "é o seu botão de desfazer, e ele custa menos que uma restauração."
confirm "Tudo funcionando e o projeto antigo preservado?"

finish
